name: waves
main: fr.orionexe.waves.Plugin
version: 0.1
api-version: 1.15
commands:
  wsolo:
    permission: waves.join.solo
  wmulti:
    permission: waves.join.multi
  wv:
    premission: waves.manage_arenas